(function () {
  "use strict";

  window.StairGameConfig = {
    highScoreKey: "stairGameHighScore",
    legacyHighScoreKey: "stair-game-high-score",
    startRow: 0,
    tileWidth: 78,
    tileHeight: 38,
    groundWidthTiles: 7,
    lookAhead: 34,
    keepBehind: 8,
    minLane: -5,
    maxLane: 5,
    baseSpeed: 1.62,
    earlySpeedBonus: 0.62,
    lateSpeedBonus: 0.95,
    earlySpeedSteps: 18,
    lateSpeedStart: 20,
    lateSpeedSteps: 85,
    fallSpeed: 650,
    inputDebounceMs: 70,
    cameraFollowSharpness: 0.001,
    shakeDuration: 0.18,
    undergroundEnd: 50,
    skyAscentEnd: 150,
    cloudRealmStart: 150,
    cloudPeakStart: 300,
    cloudChaosStart: 400,
    spaceStart: 500,
    spaceFull: 620,
    cloudBackgroundCount: 18,
    cloudMidgroundCount: 14,
    cloudForegroundCount: 7,
    cloudBackgroundMaxAlpha: 0.16,
    cloudMidgroundMaxAlpha: 0.2,
    cloudForegroundMaxAlpha: 0.24,
    seedBase: 1299721
  };
})();
